/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PoseCriteria = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'cameraAngle' : IDL.Text,
  'clothing' : IDL.Text,
  'situationFiguration' : IDL.Text,
  'situationPose' : IDL.Text,
  'lighting' : IDL.Text,
  'artStyle' : IDL.Text,
  'environment' : IDL.Text,
  'cameraLens' : IDL.Text,
  'ethnicity' : IDL.Text,
  'situationPosing' : IDL.Text,
  'negativePrompt' : IDL.Text,
  'bodyType' : IDL.Text,
  'composition' : IDL.Text,
  'situationBehavior' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const Preset = IDL.Record({
  'name' : IDL.Text,
  'criteria' : PoseCriteria,
});
export const Time = IDL.Int;
export const PromptHistory = IDL.Record({
  'timestamp' : Time,
  'criteria' : PoseCriteria,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  'getPromptHistory' : IDL.Func([], [IDL.Vec(PromptHistory)], ['query']),
  'getSituationBehaviors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'savePreset' : IDL.Func([IDL.Text, PoseCriteria], [IDL.Bool], []),
  'sendQueries' : IDL.Func([PoseCriteria, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PoseCriteria = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'cameraAngle' : IDL.Text,
    'clothing' : IDL.Text,
    'situationFiguration' : IDL.Text,
    'situationPose' : IDL.Text,
    'lighting' : IDL.Text,
    'artStyle' : IDL.Text,
    'environment' : IDL.Text,
    'cameraLens' : IDL.Text,
    'ethnicity' : IDL.Text,
    'situationPosing' : IDL.Text,
    'negativePrompt' : IDL.Text,
    'bodyType' : IDL.Text,
    'composition' : IDL.Text,
    'situationBehavior' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const Preset = IDL.Record({ 'name' : IDL.Text, 'criteria' : PoseCriteria });
  const Time = IDL.Int;
  const PromptHistory = IDL.Record({
    'timestamp' : Time,
    'criteria' : PoseCriteria,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
    'getPromptHistory' : IDL.Func([], [IDL.Vec(PromptHistory)], ['query']),
    'getSituationBehaviors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'savePreset' : IDL.Func([IDL.Text, PoseCriteria], [IDL.Bool], []),
    'sendQueries' : IDL.Func([PoseCriteria, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };